# Generated by Django 5.1.6 on 2025-03-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_banner_news_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='Range',
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(default=1, upload_to='poster_image/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
