# Generated by Django 5.1.6 on 2025-03-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_product_image_delete_range_product_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
