# Generated by Django 5.1.6 on 2025-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Notification/'),
        ),
    ]
