# Generated by Django 5.1.6 on 2025-03-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
